---
- name: Write 'hello world' to a file and print the file contents
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    target_fp: "/tmp/hello_world.txt"

  tasks:
    - name: Write 'hello world' to a file
      ansible.builtin.copy:
        content: "Hello world!"
        dest: "{{ target_fp }}"
        mode: u=rw,g=r,o=r

    - name: Print the file contents
      ansible.builtin.debug:
        # The lookup plugin only executes on the controller
        # This works because our host (localhost) is the same as the controller
        msg: "File Contents: {{ lookup('ansible.builtin.file', target_fp) }}"
