- name: Gather the host's information using facts and save to a new file using a template
  hosts: localhost
  become: false
  gather_facts: true
  vars:
    target_dir: /tmp/ansible_facts
    target_fp: "{{ target_dir }}/{{ ansible_hostname }}_facts.txt"

  tasks:
    - name: Create a directory to store the system fact files
      ansible.builtin.file:
        state: directory
        recurse: true
        path: "{{ target_dir }}"

    - name: Create a file containing facts about the host using a template
      ansible.builtin.template:
        src: system_facts_template.j2
        dest: "{{ target_fp }}"
        mode: u=rw,g=r,o=r

    - name: Read (slurp) the file content from the host
      # SLURP fetches the file from the remote host and registers its content
      # Using SLURP so the playbook can work with remote hosts
      ansible.builtin.slurp:
        src: "{{ target_fp }}"
      register: file_content_b64

    - name: Print the file contents (Decoded)
      ansible.builtin.debug:
        # Slurp returns content in Base64, so we must use the 'b64decode' filter
        msg: "File Contents: {{ file_content_b64.content | b64decode }}"
